:sparkles: add double quantity component
ZeroGachis/xamarin-ui pull request #101
Opened 2021-11-15 15:30 UTC by AudBrou

2021-11-15 15:36 UTC, valentinmagrez commented on Smartway.UiComponent/Inputs/UnbundleDoubleQuantity.xaml
> +            </DataTrigger>
il fait quoi ce datatrigger?

2021-11-15 15:52 UTC, AudBrou commented on Smartway.UiComponent/Inputs/UnbundleDoubleQuantity.xaml
> +            </DataTrigger>
Il change la couleur de la bordure ^^

2021-11-15 15:54 UTC, amelazzi commented on Smartway.UiComponent/Inputs/UnbundleDoubleQuantity.xaml.cs
> +        public static readonly BindableProperty LeftQuantityProperty = BindableProperty.Create(nameof(LeftQuantity), typeof(int?), typeof(UnbundleDoubleQuantity));
ligne un peu trop longue :3

2021-11-15 16:15 UTC, valentinmagrez approved these changes

2021-11-15 16:34 UTC, sGeeK44 requested changes
Je trouve le nom du composant douteux ! Il fait plutôt penser à un composant qui permet de saisir une quantité sur une quantité maximum (indépendamment du délottage ;))

Et un petit gif pour voir les animations ça aurait pu être cool :)

2021-11-15 16:34 UTC, sGeeK44 commented on Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml
> +                        <inputs:UnbundleDoubleQuantity LeftQuantity="{Binding BundleQuantity}"
Plutôt que Left et Right on pourrait pas avoir plutôt, `Current` ou `Input` et `Total` ? enfin un truc qui ressemble plus au composant "générique".

2021-11-17 17:16 UTC, sGeeK44 approved these changes

2021-11-17 17:40 UTC, merged