:bug: :lipstick: NumericDateEntry - Fix spanish format
ZeroGachis/xamarin-ui pull request #140
Opened 2022-10-06 09:35 UTC by amelazzi

The spanish format was displayed as mm/dd/yy because we were checking if the clutur format is 'd MMMM' although the spanish format is 'd de MMMM'

2022-10-06 09:58 UTC, tuxtoby commented on Smartway.UiComponent/Inputs/NumericDateEntry.xaml.cs
> +            return calendarType.IndexOf("d") < calendarType.IndexOf("M");
Yep j'allais dire pareil que françois, go TU avec une liste au dessus du TU pour tester tous les formats possible que c'est OK (genre les ~10 cultures les plus utilisées qu'on aura à priori)

2022-10-06 12:09 UTC, sGeeK44 requested changes

2022-10-06 12:09 UTC, sGeeK44 commented on Smartway.UiComponent.UnitTests/Inputs/NumericDateInput/NumericDateEntryTest.cs
> +        }
Je pense qu'il faut plutôt tester la valeur du default input et non pas le détail de comment on le gère.
En gros pour moi il faut plus un test:
```
        [Theory]
        [InlineData("fr-FR", "JJ", "MM", "AA")]
        [InlineData("es-ES", "??", "MM", "??")]
        [InlineData("it-IT", "??", "MM", "??")]
        [InlineData("ru-RU", "??", "MM", "??")]
        [InlineData("ro-RO", "??", "MM", "??")]
        [InlineData("us-US", "DD", "MM", "YY")]
        [InlineData("en-EN", "DD", "MM", "YY")]
        public void DayMonthCulture(string culture, string day, string month, string year)
        {
            Thread.CurrentThread.CurrentCulture = new CultureInfo(culture);
            var numericDateEntry= new NumericDateEntry();

            Check.That(numericDateEntry.DayEntry.Placeholder).IsEqualTo(day);
            Check.That(numericDateEntry.MonthEntry.Placeholder).IsEqualTo(month);
            Check.That(numericDateEntry.YearEntry.Placeholder).IsEqualTo(year);
        }
```

2022-10-06 20:12 UTC, sGeeK44 requested changes
Déso 😅

2022-10-06 20:12 UTC, sGeeK44 commented on Smartway.UiComponent/Inputs/NumericDateEntry.xaml.cs
> +        public bool IsDayMonthCalendar()
Du coup c'est plus nécessaire non ?

2022-10-07 08:10 UTC, amelazzi commented on Smartway.UiComponent/Inputs/NumericDateEntry.xaml.cs
> +        public void SetupEntries()
on passe dans le constructeur tout au début du test et à ce moment là, la culture n'est pas encore set à fr, es, .... du coup on ne récupère pas le bon format :/

2022-10-07 08:17 UTC, tuxtoby commented on Smartway.UiComponent.UnitTests/Inputs/NumericDateInput/NumericDateEntryTest.cs
> +            SetUpDate(culture);
Pour le couup c'est interessant là d'avoir le 06/10/22 dans le SetuoDate que l'on vient check juste après ^^

2022-10-07 08:19 UTC, tuxtoby commented on Smartway.UiComponent/Inputs/NumericDateEntry.xaml.cs
> +            return calendarType.IndexOf("d") < calendarType.IndexOf("M");
J'aurais bien fait une fonction privée qui donne l'intention exacte de pourquoi faire ça, là perso en lisant ça je comprends pas pourquoi on fait ça ^^

2022-10-07 08:22 UTC, tuxtoby commented on Smartway.UiComponent/Inputs/NumericDateEntry.xaml.cs
>              return date.Year == 1;
Même commentaire que plus bas, plutôt qu'un com, j'aurais bien mis une fonction qui donne l'intention (les com y'a plein de raisons qui font que c'est très très rarement une bonne idée)

Je sais que c'est pas toi qui a fait ça donc limite un 2eme commit pour le faire, car je me dis que c'est pas demain la veille qu'on va retoucher à ce composant pour le clean ^^

2022-10-07 08:24 UTC, sGeeK44 commented on Smartway.UiComponent/Inputs/NumericDateEntry.xaml.cs
> +            return calendarType.IndexOf("d") < calendarType.IndexOf("M");
Bah pour le coup c'est `IsDayMonthCalendar`. Pour le coup je trouve ça assez lisible là.

2022-10-07 08:26 UTC, sGeeK44 commented on Smartway.UiComponent/Inputs/NumericDateEntry.xaml.cs
>              return date.Year == 1;
D'accord avec Thomas, c'est pas de toi, mais si on applique la boys scout rule tu peux remplacer ce commentaire par `return date.Year == DateTime.MinValue.Year;`

2022-10-07 09:18 UTC, sGeeK44 commented on Smartway.UiComponent/Inputs/NumericDateEntry.xaml.cs
> +        public void SetupEntries()
Je pense que le test est "mal conçu" à la base. Déjà il faut mieux éviter les fonctions avec effet de bord (ça rend pas très lisible le test, mais plutôt utiliser des fonctions pures.
Exemple
```
        [Theory]
        [InlineData("fr-FR", "06", "10")]
        [InlineData("us-US", "10", "06")]
        public void MonthDayOrderCulture(string culture, string expectedFirst, string expectedSecond)
        {
            SetCulture(culture);

            var entry = CreateNumericDateEntry("06", "10", "2022");

            CheckNumericDateEntry(entry, expectedFirst, expectedSecond, "2022");
        }

        private void SetCulture(string culture)
        {
            Thread.CurrentThread.CurrentCulture = new CultureInfo(culture);
            Thread.CurrentThread.CurrentUiCulture = new CultureInfo(culture);
        }

       private void CreateNumericDateEntry(string day, string month, string year)
        {
            var numericDateEntry = new NumericDateEntry();
            var numericDateEntry.DayEntry.Text = day;
            var numericDateEntry.MonthEntry.Text = month;
            var numericDateEntry.YearEntry.Text = year;
        }

       private void CheckNumericDateEntry(NumericDateEntry entry, string expectedFirst, string expectedSecond, string expectedThird)
        {
            CheckEntry(entry, "FirstEntry", expectedFirst);
            CheckEntry(entry, "SecondEntry", expectedSecond);
            CheckEntry(entry, "ThirdEntry", expectedThird);
        }

       private void CheckEntry(NumericDateEntry entry, string name, string expectedValue)
       {
            var value = (Entry)entry.FindByName(name);
            Check.That(value .Text).IsEqualTo(expectedValue);
       }
```

2022-10-07 10:09 UTC, sGeeK44 approved these changes

2022-10-07 11:42 UTC, tuxtoby approved these changes

2022-10-07 12:02 UTC, merged