Fix/expander cart list
ZeroGachis/xamarin-ui pull request #15
Opened 2020-11-04 22:30 UTC by valentinmagrez

![expanderlist](https://user-images.githubusercontent.com/10033411/98174602-6aa5be80-1ef5-11eb-821e-d23e2b34a5b3.gif)

Bon désolé c'est un composant un peu bourrin que j'ai rajouté.

Pour avoir l'affichage des elements de maniere asynchrone j'ai du bosser avec deux listes dans le composant et pour empecher  l'ui de freeze quand on bourrine les observableCollection à coup de Add je suis obligé je rajouter des task.delay :/

2020-11-05 07:23 UTC, sGeeK44 commented on Smartway.UiComponent/CardLists/ExpanderCardList.xaml.cs
> +        private readonly Queue<ObservableCollectionAction<IProductViewModel>> _actionToExecute = new Queue<ObservableCollectionAction<IProductViewModel>>();
L'expander card ne doit pas être lié à un IProductViewModel.
D'ailleur il ne doit être lié à aucune view model. c'est le principe même de Mvvm

2020-11-05 07:23 UTC, sGeeK44 commented on Smartway.UiComponent/Cards/IProductViewModel.cs
> +    public interface IProductViewModel
No way :)

2020-11-09 07:43 UTC, sGeeK44 approved these changes
👌

2020-11-09 07:43 UTC, sGeeK44 commented on Smartway.UiComponent/Layouts/ScannableLayout.xaml.cs
> +        public  View LayoutContent
manque un retour à la ligne.

2020-11-09 07:44 UTC, sGeeK44 commented
Ce qui aurait pu être cool c'est de rajouter le gif pour les deux nouveaux composants

2020-11-09 08:16 UTC, a-bertrand requested changes
Je ne sais pas si l'image est encore contractuel mais le texte du warning n'est pas orange ^^ '

2020-11-09 09:03 UTC, valentinmagrez commented
> Je ne sais pas si l'image est encore contractuel mais le texte du warning n'est pas orange ^^ '

AH !

2020-11-09 14:07 UTC, merged