✨ ♻️  💥CardList with customizable itemLayout
ZeroGachis/xamarin-ui pull request #19
Opened 2020-11-10 16:06 UTC by pewho

Attention, casse l'actuel ArticleCardList (changement Relativement simple, néanmoins)

2020-11-10 16:34 UTC, a-bertrand commented on Smartway.UiComponent/CardLists/ArticleCardList.xaml.cs
> +            } catch (InvalidCastException ex) { }
Pourquoi ce try catch ? et c'est quoi ce "OnPropertyChanged(nameof(ArticlesList));" ça remplace le if e.PropertyName == "AlertList" ?

2020-11-10 16:35 UTC, a-bertrand commented on Smartway.UiComponent/CardLists/ArticleCardList.xaml
> +             x:Name="List"
vraiment utile ce x:Name ?

2020-11-10 16:35 UTC, a-bertrand commented on Smartway.UiComponent/CardLists/ArticleCardList.xaml
> +                     x:Name="ArticleListElement"
Elemnts ?

2020-11-10 16:37 UTC, a-bertrand requested changes
Petites remarques

2020-11-10 16:44 UTC, pewho commented on Smartway.UiComponent/CardLists/ArticleCardList.xaml
> +             x:Name="List"
yep, pour les binding plus bas

2020-11-10 16:46 UTC, pewho commented on Smartway.UiComponent/CardLists/ArticleCardList.xaml.cs
> +            } catch (InvalidCastException ex) { }
pour le try catch : si il n'est pas la, dans le cas de l'expanderCard, la liste est rendue a priori une première fois sans article. Dans ce cas, il n'y a pas de template rendu, et le cast échoue (et fait crasher l'app). Cela permet de l’éviter.
Le propertiesChanged, c'est une bonne question. Je l'ai dégagé, ça marche sans ...

2020-11-12 08:27 UTC, a-bertrand commented on Smartway.UiComponent/CardLists/ArticleCardList.xaml.cs
> +            } catch (InvalidCastException ex) { }
humm j'ai pas compris mais je ne pense pas que ce try catch soit la solution peut être le test e.PropertyName == "AlertList" && ...Children.count() > 0 ?

2020-11-12 09:06 UTC, pewho commented on Smartway.UiComponent/CardLists/ArticleCardList.xaml.cs
> +            } catch (InvalidCastException ex) { }
Alors j'ai fait un fix, mais c'est pas ouf

2020-11-12 10:12 UTC, closed without merging