Fix/adjust the card list articles ui
ZeroGachis/xamarin-ui pull request #26
Opened 2020-11-23 16:48 UTC by azertyValentin

2020-11-23 17:34 UTC, EwenBALOUIN requested changes
c'est good mais tu peux enlever du code

2020-11-23 17:34 UTC, EwenBALOUIN commented on Smartway.UiComponent/CardLists/ArticleCardList.xaml
> +                               </DataTrigger>
au lieu de faire un deuxième data triggers met par default la margin bot à 20

2020-11-24 08:40 UTC, azertyValentin commented on Smartway.UiComponent/CardLists/ArticleCardList.xaml
> +                               </DataTrigger>
bien vu

2020-11-24 10:31 UTC, valentinmagrez approved these changes

2020-11-24 10:36 UTC, merged