ModalPage Component
ZeroGachis/xamarin-ui pull request #29
Opened 2020-12-08 17:28 UTC by pewho

![device-2020-12-08-182322](https://user-images.githubusercontent.com/1177510/101519012-f1313e00-3982-11eb-8424-f38bbe877b97.png)

J'ai colorié le background de chaque élément pour voir la taille occupé. Le body est variable en hauteur, avec une limite max de 16px en margin en haut et en bas...

2020-12-08 17:32 UTC, pewho commented
Il y a potentiellement des trucs a améliorer : 
- On pourrait rendre les backgrounds color de la page et de la frame dynamiques
- Il y a des séparateurs en haut et en bas du body, je ne suis pas sur que on les ajoute ici ou dans les implementations ...

2020-12-09 09:11 UTC, a-bertrand requested changes

2020-12-09 09:13 UTC, a-bertrand commented on Smartway.UiComponent/Pages/ModalPage.xaml
> +<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
Faut virer le header de navigation par défaut

2020-12-09 14:13 UTC, pewho commented
Je suis en attente des etats desactivés pour le cancel button...

2020-12-09 14:17 UTC, a-bertrand commented on Smartway.UiComponent/Pages/ModalPage.xaml
> +             BackgroundColor="Black">
C'est pas tout a fait noir sur la maquette je crois

2020-12-09 14:24 UTC, a-bertrand reviewed
Je ne sais pas si c'est du a tes changements mais il y a le texte par exemple de large button qui est ocupé au niveau du g

2020-12-09 14:26 UTC, pewho commented on Smartway.UiComponent/Pages/ModalPage.xaml
> +             BackgroundColor="Black">
https://xd.adobe.com/view/07d02e39-fb14-49f3-ae8d-574142e25ea7-5283/screen/93ad8a6c-077a-49e2-8ea4-31354ccc402a/specs/ d'apres XD si, mais c'est bizarre, je confirmerais avec Helene

2020-12-09 15:45 UTC, pewho commented on Smartway.UiComponent/Pages/ModalPage.xaml
> +             BackgroundColor="Black">
et la reponse est 80% d'opacité (non visible sur le XD)

2020-12-09 16:44 UTC, merged