Feature/input forms element
ZeroGachis/xamarin-ui pull request #31
Opened 2020-12-10 14:37 UTC by tuxtoby

2020-12-10 15:03 UTC, valentinmagrez commented on Smartway.UiComponent/FormsElements/FormElement.xaml
> +            <Grid Margin="0,-10,0, 0"  ColumnSpacing="0" RowSpacing="-11">
les margin negatifs souvent un code smell de "on comprend pas trop mais ca marche comme ca"

2020-12-10 15:03 UTC, valentinmagrez commented on Smartway.UiComponent/FormsElements/FormElement.xaml
> +            <Grid Margin="0,-10,0, 0"  ColumnSpacing="0" RowSpacing="-11">
ah! le rowspacing negatif aussi ?

2020-12-10 15:09 UTC, pewho requested changes
- Je pense que la couleur de l'helper Text n'est pas bonne (elle est normalement grise #707070)
- J'ai un doute sur le nom ('input form semble etre le nom du groupe de component, je l'aurais plus appelé TextInput, ou qq chose dans le genre)

2020-12-10 15:09 UTC, pewho commented on Smartway.UiComponent.Sample/FormsElements/FormElement.xaml
> +            <formsElements:FormElement Title="Disabled" Prefix="€" Helper="Helper text" PlaceHolder="This is a placeholder" Disabled="True"></formsElements:FormElement>
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager Ce ne serait pas mieux de gérer les etats avec ça ? (je ne sais pas si c'est une bonne idée, c'est une question ouverte )

2020-12-10 15:09 UTC, tuxtoby commented on Smartway.UiComponent/FormsElements/FormElement.xaml
> +            <Grid Margin="0,-10,0, 0"  ColumnSpacing="0" RowSpacing="-11">
dixit le mec qui met pas de verbe dans ses phrases

2020-12-10 15:09 UTC, valentinmagrez commented on Smartway.UiComponent/FormsElements/FormElement.xaml.cs
> +        public static readonly BindableProperty ReadOnlyProperty = BindableProperty.Create(nameof(ReadOnly), typeof(bool), typeof(FormElement), false);
pas besoin du false a la fin, un booleen est faux par defaut

2020-12-10 15:09 UTC, valentinmagrez commented on Smartway.UiComponent/FormsElements/FormElement.xaml.cs
> +        public static readonly BindableProperty DisabledProperty = BindableProperty.Create(nameof(Disabled), typeof(bool), typeof(FormElement), false, propertyChanged: DisabledMode);
pareil ici

2020-12-10 15:09 UTC, valentinmagrez commented on Smartway.UiComponent/FormsElements/FormElement.xaml.cs
> +        public static readonly BindableProperty ErrorProperty = BindableProperty.Create(nameof(Error), typeof(string), typeof(FormElement), "", propertyChanged: ErrorMessage);
plutot que "", utiliser string.empty

2020-12-10 15:14 UTC, valentinmagrez commented on Smartway.UiComponent/FormsElements/FormElement.xaml
> +            <Grid Margin="0,-10,0, 0"  ColumnSpacing="0" RowSpacing="-11">
pas le temps de mettre des verbes, trop de commentaire à mettre!

2020-12-10 15:14 UTC, valentinmagrez commented on Smartway.UiComponent/FormsElements/FormElement.xaml
> +﻿<?xml version="1.0" encoding="utf-8" ?>
UN peu comme mathias je trouve le nom un peu trop large, sachante que ca n'a l'air de ciblé que les entry

2020-12-10 15:17 UTC, valentinmagrez commented on Smartway.UiComponent/FormsElements/FormElement.xaml.cs
> +                var GrayColor = Color.FromHex("#B2B2B2");
variable local en camelCase

2020-12-10 15:29 UTC, valentinmagrez commented on Smartway.UiComponent/FormsElements/FormElement.xaml.cs
> +                FormElement.HelperLabel.Text = (string) newValue;
on va préferer un datatrigger "si error n'est pas vide afficher error sinon helper" que de faire ce petit bout de code plein de subtilité ^^

2020-12-10 15:29 UTC, valentinmagrez requested changes
.

2020-12-10 15:46 UTC, a-bertrand commented on Smartway.UiComponent.Sample.Android/CustomentryRenderer.cs
> +using Xamarin.Forms.Platform.Android;
A voir mais je pense qu'il y a peut être des imports useless !

2020-12-10 15:48 UTC, a-bertrand commented on Smartway.UiComponent.Sample/FormsElements/FormElement.xaml.cs
> +using Xamarin.Forms.Xaml;
pareil ici sur les imports

2020-12-10 15:50 UTC, a-bertrand commented on Smartway.UiComponent/FormsElements/FormElement.xaml
> +            <Grid Margin="0,0,0,-17"  ColumnSpacing="0" RowSpacing="-11">
Sur les margin négatif je trouve ça plus lisible de mettre des padding positif aux parents généralement un margin négatif ça permet de montrer genre un petit trick pour faire chevaucher deux élèments.

2020-12-10 15:54 UTC, a-bertrand commented on Smartway.UiComponent/FormsElements/FormElement.xaml
> +            <Grid Margin="0,-10,0, 0"  ColumnSpacing="0" RowSpacing="-11">
Je suis daccord sur les margin négatif et pour djustifie run peu, c'est plus lisible de mettre des padding positif aux parents généralement, qu'un margin négatif. C'est plus utilisé pour montrer un petit trick pour faire chevaucher deux éléments.

2020-12-10 15:56 UTC, a-bertrand commented on Smartway.UiComponent/FormsElements/FormElement.xaml
> +                <Label Grid.Column="0" x:Name="PrefixLabel" Text="{Binding Source={x:Reference Self}, Path=Prefix}" HorizontalTextAlignment="Center" VerticalTextAlignment="Center" FontSize="16" Margi
Pour que ce soit plus lisible au premier coup d'oeil ce serai cool de mettre un max de style dans les ressources stp

2020-12-10 16:52 UTC, valentinmagrez commented on Smartway.UiComponent/FormsElements/FormElement.xaml.cs
> +                formElement._helperMessage = (string) oldValue;
toujours present ! toujours debout !

2020-12-10 16:53 UTC, valentinmagrez commented on Smartway.UiComponent/FormsElements/FormElement.xaml
> +                    <DataTrigger TargetType="Label" Binding="{Binding Source={x:Reference Self}, Path=Error,Converter={StaticResource HasErrorMessage}}" Value="True">
plutot qu'avoir un converter on peut pas juste checker que error="" ?

2020-12-11 08:58 UTC, tuxtoby commented on Smartway.UiComponent/FormsElements/FormElement.xaml
> +                    <DataTrigger TargetType="Label" Binding="{Binding Source={x:Reference Self}, Path=Error,Converter={StaticResource HasErrorMessage}}" Value="True">
J'ai inversé le check pour virer le converter :)

2020-12-11 08:58 UTC, tuxtoby commented on Smartway.UiComponent/FormsElements/FormElement.xaml.cs
> +                formElement._helperMessage = (string) oldValue;
Oups, c'est bon maintenant

2020-12-11 09:01 UTC, ducdetronquito commented
Est-ce que vous pourriez réduire cette PR à quelques commits bien clairs ?
C'est pas simple à review ^^

2020-12-11 13:19 UTC, pewho commented on Smartway.UiComponent.Sample.Android/CustomentryRenderer.cs
> +    public class CustomEntryRenderer : EntryRenderer
Le nom du fichier ne devrait pas etre `CustomEntryRenderer` ?

2020-12-11 13:23 UTC, tuxtoby commented on Smartway.UiComponent.Sample.Android/CustomentryRenderer.cs
> +    public class CustomEntryRenderer : EntryRenderer
Ah, fail de refacor merci

2020-12-11 13:24 UTC, pewho commented on Smartway.UiComponent/FormsElements/ZgEntry.xaml
> +                <Setter Property="Margin" Value="-4,2,0,0"/>
Avec mes yeux d'elfe, je vois des Margins negatives 😨

2020-12-11 13:24 UTC, pewho commented on Smartway.UiComponent/FormsElements/ZgEntry.xaml
> +            <Grid ColumnSpacing="0" RowSpacing="-10" Margin="0,-6,0,0">
La aussi

2020-12-11 13:26 UTC, tuxtoby commented on Smartway.UiComponent/FormsElements/ZgEntry.xaml
> +            <Grid ColumnSpacing="0" RowSpacing="-10" Margin="0,-6,0,0">
J'ai dit hier que j'avais pu en enlever, mais que j'avais dû en remettre, et que j'étais preneur si vous saviez comment faire autrement, car on ne trouvait pas d'autres solutions avec Ewen :)

2020-12-11 13:26 UTC, valentinmagrez commented on Smartway.UiComponent/FormsElements/ZgEntry.xaml.cs
> +    public partial class ZgEntry
je vais etre relou sur le naming, mais je suis pas fan de prefixé les composants par Zg, on l'a jamais fait jusque la en plus. Je proposerai bien FormEntry, car c'est une entry qui a pour but d'etre dans un formulaire avec le coté valdiation et message d'erreur

2020-12-11 13:42 UTC, ducdetronquito commented on Smartway.UiComponent.Sample.Android/Smartway.UiComponent.Sample.Android.csproj
> +      <UserProperties TriggeredFromHotReload="False" XamarinHotReloadUnhandledDeviceExceptionSmartwayUiComponentSampleAndroidHideInfoBar="True" />
Ca on veut pas le commiter :P

2020-12-11 13:42 UTC, ducdetronquito commented on Smartway.UiComponent/FormsElements/ZgEntry.xaml
> +            <Label x:Name="TitleLabel" Text="{Binding Source={x:Reference  Self}, Path=Title}" Style="{StaticResource Title}"></Label>
La propriété `x:Name` pourrait être juste `Title` non ?

2020-12-11 21:02 UTC, valentinmagrez approved these changes

2020-12-14 08:55 UTC, pewho approved these changes

2020-12-14 10:41 UTC, sGeeK44 requested changes

2020-12-14 10:41 UTC, sGeeK44 commented on Smartway.UiComponent/FormsElements/FormEntry.xaml
> +﻿<?xml version="1.0" encoding="utf-8" ?>
J'aurais plutôt ajouté ce composant dans le dossier Inputs non ?

2020-12-14 10:41 UTC, sGeeK44 commented on Smartway.UiComponent/FormsElements/FormEntry.xaml.cs
> +            EntryDividerPrefix.BackgroundColor = Color.FromHex("#E2E4F0");
Est-ce qu'on avoir une constante plutôt que le hast tag directe plz.

exemple:

```
public static readonly Color Red = Color.FromHex("#E2E4F0");

```

2020-12-14 10:41 UTC, sGeeK44 commented on Smartway.UiComponent/FormsElements/FormEntry.xaml.cs
> +                var grayColor = Color.FromHex("#B2B2B2");
Idem.

2020-12-14 13:37 UTC, sGeeK44 commented on Smartway.UiComponent/Inputs/FormEntry.xaml.cs
> +        public static readonly Color DividerColor = Color.FromHex("#E2E4F0");
C'est plutôt le nom de couleur qui serait intéressant ici je pense.
Surtout si on devait l'utiliser pour un autre élément dans la vue, on serait bien embêté.

2020-12-14 13:38 UTC, sGeeK44 approved these changes

2020-12-14 14:47 UTC, merged