Hotfix/input forms element helene feedback
ZeroGachis/xamarin-ui pull request #34
Opened 2020-12-15 16:25 UTC by tuxtoby

2020-12-15 16:34 UTC, sGeeK44 requested changes

2020-12-15 16:34 UTC, sGeeK44 commented on Smartway.UiComponent/Inputs/FormEntry.xaml.cs
> +            BindableProperty.Create(nameof(Helper), typeof(string), typeof(FormEntry), string.Empty);
ca change quoi de mettre ça ? la valeur null ne convenait pas ?

2020-12-15 16:34 UTC, sGeeK44 commented on Smartway.UiComponent/Inputs/FormEntry.xaml.cs
> +        }
Manque un retour à la ligne.

2020-12-15 16:34 UTC, sGeeK44 commented on Smartway.UiComponent/Inputs/FormEntry.xaml.cs
> +        public string Type
On a quoi comme valeur possible ? On peut pas mettre un enum plutôt ?

2020-12-15 16:37 UTC, tuxtoby commented on Smartway.UiComponent/Inputs/FormEntry.xaml.cs
> +        public string Type
Select (On met une flèche au bout, et l'utilisateur du composant met un event pour faire apparaitre une popup de choix) et Input (le cas normal)

2020-12-15 16:39 UTC, tuxtoby commented on Smartway.UiComponent/Inputs/FormEntry.xaml.cs
> +            BindableProperty.Create(nameof(Helper), typeof(string), typeof(FormEntry), string.Empty);
Si on met null, ça ne trigge pas le DataTrigger qui fait disparaitre l'élement si le HelperText est vide (string.empty != null)

2020-12-15 16:39 UTC, tuxtoby commented on Smartway.UiComponent/Inputs/FormEntry.xaml.cs
> +        }
Done

2020-12-16 09:22 UTC, sGeeK44 approved these changes

2020-12-16 09:34 UTC, merged