:sparkles: Add binding for nodialogdatepicker
ZeroGachis/xamarin-ui pull request #47
Opened 2021-01-19 17:40 UTC by valentinmagrez

2021-01-19 20:21 UTC, sGeeK44 requested changes

2021-01-19 20:21 UTC, sGeeK44 commented on Smartway.UiComponent.Droid/Renderers/NoDialogDatePickerRenderer.cs
> +                LinkDatePickerToAndroidControl(e.NewElement);
Faudrait pas supprimer la soucription de l'évènement quelque part ?

2021-01-19 20:21 UTC, sGeeK44 commented on Smartway.UiComponent.Droid/Renderers/NoDialogDatePickerRenderer.cs
> +            if (newDate == Element.Date)
on peut changer l'ordre ? `if (newDate == Element.Date)` => `if (Element.Date == newDate)`

2021-01-19 20:21 UTC, sGeeK44 commented on Smartway.UiComponent.Droid/Renderers/NoDialogDatePickerRenderer.cs
> +        private long ConvertDateToJavaFormat(DateTime date)
Le plaisir :)

2021-01-19 20:21 UTC, sGeeK44 commented on Smartway.UiComponent.Droid/Renderers/NoDialogDatePickerRenderer.cs
> +            Control.MinDate = ConvertDateToJavaFormat(element.MinimumDate);
Si la MinDate change, ce sera pas propagé au control natif ?

2021-01-19 21:42 UTC, valentinmagrez commented on Smartway.UiComponent.Droid/Renderers/NoDialogDatePickerRenderer.cs
> +            Control.MinDate = ConvertDateToJavaFormat(element.MinimumDate);
en regardant un peu le code source du datepicker renderer de base j'ai trouvé comment eux faisait: 
DatePicker.MinDate = (long)Element.MinimumDate.ToUniversalTime().Subtract(DateTime.MinValue.AddYears(1969)).TotalMilliseconds; 
Je trouve ma version plus lisible!

2021-01-19 22:25 UTC, valentinmagrez commented on Smartway.UiComponent.Droid/Renderers/NoDialogDatePickerRenderer.cs
> +        private long ConvertDateToJavaFormat(DateTime date)
en regardant un peu le code source du datepicker renderer de base j'ai trouvé comment eux faisait:
DatePicker.MinDate = (long)Element.MinimumDate.ToUniversalTime().Subtract(DateTime.MinValue.AddYears(1969)).TotalMilliseconds;
Je trouve ma version plus lisible!

2021-01-20 07:23 UTC, sGeeK44 approved these changes

2021-01-20 07:24 UTC, sGeeK44 commented on Smartway.UiComponent.Droid/Renderers/NoDialogDatePickerRenderer.cs
> +            Control.MinDate = ConvertDateToJavaFormat(element.MinimumDate);
Faudra y penser si on a besoin de cette feature.

2021-01-20 08:56 UTC, merged