🐛 fix position label with no image
ZeroGachis/xamarin-ui pull request #62
Opened 2021-02-09 15:50 UTC by EwenBALOUIN

![image](https://user-images.githubusercontent.com/46872095/107389232-e87df500-6af6-11eb-9e01-39e6365dfa4e.png)

2021-02-09 15:53 UTC, tuxtoby commented on Smartway.UiComponent/TopAppBar/TopAppBar.xaml
> +                <Setter Property="Margin" Value="0, 0, 32, 0"></Setter>
Mettre /> à la fin

2021-02-09 15:55 UTC, Keivhin requested changes

2021-02-09 15:55 UTC, Keivhin commented on Smartway.UiComponent.Sample/TopAppBar/Views/TopAppBar.xaml
> +                Title="no image button"
Pourquoi mettre ça à la ligne comme ça ? C'est sauvage 😢

2021-02-09 15:55 UTC, Keivhin commented on Smartway.UiComponent/TopAppBar/TopAppBar.xaml
> +                <Setter Property="Margin" Value="0, 0, 32, 0"></Setter>
Sur une ligne please !

2021-02-09 15:59 UTC, pewho commented on Smartway.UiComponent/TopAppBar/TopAppBar.xaml.cs
> +        public static readonly BindableProperty IconSourceProperty = BindableProperty.Create(nameof(IconSource), typeof(string), typeof(TopAppBar), String.Empty);
la valeur null fait péter d'où le defaut à "" ?

2021-02-09 16:14 UTC, EwenBALOUIN commented on Smartway.UiComponent/TopAppBar/TopAppBar.xaml.cs
> +        public static readonly BindableProperty IconSourceProperty = BindableProperty.Create(nameof(IconSource), typeof(string), typeof(TopAppBar), String.Empty);
c'est surtout qu'on peut pas faire un trigger sur cette valeur

2021-02-10 12:48 UTC, Keivhin approved these changes

2021-02-10 14:14 UTC, merged