Feature/use icon on topappbar
ZeroGachis/xamarin-ui pull request #66
Opened 2021-02-10 17:13 UTC by EwenBALOUIN

![image](https://user-images.githubusercontent.com/46872095/107545482-a5418600-6bcb-11eb-9e10-5d12882751b2.png)

2021-02-10 18:08 UTC, sGeeK44 commented on Smartway.UiComponent/Labels/Icons/Icon.xaml.cs
> +            Workspaces,
`Workspace` c'est un terme métier. faudrait plutôt un nom qui représente l'icon

2021-02-11 08:28 UTC, tuxtoby commented on Smartway.UiComponent/Labels/Icons/Icon.xaml.cs
> +            Workspaces,
C'est le nom de l'icône :)

2021-02-11 08:28 UTC, Keivhin commented on Smartway.UiComponent/Labels/Icons/Icon.xaml.cs
> +            Workspaces,
https://material.io/resources/icons/?search=workspaces&icon=workspaces&style=baseline C'est bien ça !

2021-02-11 08:46 UTC, tuxtoby approved these changes

2021-02-11 09:02 UTC, sGeeK44 approved these changes

2021-02-11 09:26 UTC, Keivhin requested changes
Supprime les png stp :)

2021-02-11 10:06 UTC, tuxtoby commented on Smartway.UiComponent/Buttons/ScanButton.xaml
>                  <TapGestureRecognizer Command="{Binding Source={Reference Self}, Path=Command}"></TapGestureRecognizer>
Finir par />

2021-02-11 10:08 UTC, tuxtoby approved these changes

2021-02-11 10:11 UTC, Keivhin approved these changes

2021-02-11 10:44 UTC, merged