Feature/add expander card
ZeroGachis/xamarin-ui pull request #7
Opened 2020-10-22 17:47 UTC by a-bertrand

![image](https://user-images.githubusercontent.com/4598358/96909823-d96b2c80-149e-11eb-8efc-0feb3dcf9280.png)

2020-10-23 07:15 UTC, sGeeK44 requested changes
Les composants, y'a pas à dire ça a de la gueule !
![tenor](https://user-images.githubusercontent.com/8371625/96967791-52569c80-1510-11eb-91f6-a60390eb8989.gif)

2020-10-23 07:15 UTC, sGeeK44 commented on Smartway.UiComponent.Sample/ExpanderCard/ExpanderCardSample.xaml
> +                    <cards:ExpanderCard Title="basic title with Content title with Content" Counter="2">
Je trouve ça dommage que ce soit pas dans le composant par défaut.

2020-10-23 07:15 UTC, sGeeK44 commented on Smartway.UiComponent/Cards/ExpanderCard.xaml
> +                    <Image IsVisible="false" Margin="0,0,10,0"  WidthRequest="24" HeightRequest="24" HorizontalOptions="Start" Source="{utils:ImageResource Source=Smartway.UiComponent.Resources.Icons
Tu veux pas mettre les styles séparer dans le début du fichier ? (Margin Height, etc...)
Je trouve que ça apporte en lisibilité.

2020-10-23 07:15 UTC, sGeeK44 commented on Smartway.UiComponent/Cards/ExpanderCard.xaml
> +                            <Setter Property="Rotation" Value="180" />
Ca fait quoi ça ?

2020-10-23 07:15 UTC, sGeeK44 commented on Smartway.UiComponent/Cards/ExpanderCard.xaml.cs
> +                HeightRequest = 328;
Wat ?

2020-10-23 07:15 UTC, sGeeK44 commented on Smartway.UiComponent/Cards/ExpanderCard.xaml.cs
> +                HeightRequest = 328;
Avoid magic number plz ;)

2020-10-23 07:15 UTC, sGeeK44 commented on Smartway.UiComponent/Cards/RoundedFrame.xaml
> +    Padding="16,20,16,20"
Est-ce que ça pourrait pas être dans un style général genre `RoundedElement` ? car il me semble qu'on l'utilise déjà dans d'autre élément (`Section` peut-être).

2020-10-23 07:15 UTC, sGeeK44 commented on Smartway.UiComponent/Smartway.UiComponent.csproj
> +    <None Remove="Resources\Icons\orange_icon_warning.png" />
Je suis pas sur que ce soit utile vu qu'ils sont déjà en embedded

2020-10-23 08:02 UTC, valentinmagrez commented on Smartway.UiComponent.Sample/ExpanderCard/ExpanderCardSample.xaml
> +                    <cards:ExpanderCard Title="basic title with Content title with Content" Counter="2">
qu'est que tu voudrais mettre dans le composant de base ?

2020-10-23 08:10 UTC, valentinmagrez commented on Smartway.UiComponent/Cards/ExpanderCard.xaml
> +    <Expander.Header>
question con mais ce .Header c'est quoi c'est une propriété des composants par défaut ?

2020-10-23 08:11 UTC, valentinmagrez commented on Smartway.UiComponent/Cards/ExpanderCard.xaml
> +            <ResourceDictionary.MergedDictionaries>
On a besoin du MergedDctionary vu que tu en ajoutes que un ?

2020-10-23 08:21 UTC, a-bertrand commented on Smartway.UiComponent/Cards/ExpanderCard.xaml
> +    <Expander.Header>
Oui c'est ça !

2020-10-23 08:30 UTC, a-bertrand commented on Smartway.UiComponent/Cards/ExpanderCard.xaml
> +            <ResourceDictionary.MergedDictionaries>
Ouai c'est pour merge les couleurs avec ce que je définis. Je suis d'accord ça semble un peu abusé mais je ne sais pas comment faire autrement. Car c'est pour quand on va l'utiliser dans l'appli on utilise bien la couleur du thème :s.
Idéalement j'aimerai bien définir une couleur générique et qui dépend du thème ( je vais essayer de voir avec François si on a pas une solution un peu plus sexy).

2020-10-23 14:52 UTC, a-bertrand commented on Smartway.UiComponent/Cards/ExpanderCard.xaml
> +                            <Setter Property="Rotation" Value="180" />
ça tourne l'image de 180 pour éviter d'utiliser deux images ( pour le drop vers le haut puis le bas )

2020-10-23 14:53 UTC, a-bertrand commented on Smartway.UiComponent/Smartway.UiComponent.csproj
> +    <None Remove="Resources\Icons\orange_icon_warning.png" />
Heu je ne sais pas c'cest visual qui les add auto ( voir plus bas c'est la même chose pour le reste )

2020-10-26 09:18 UTC, pewho approved these changes

2020-10-26 09:19 UTC, pewho commented
elle est juste a rebase

2020-10-26 09:29 UTC, valentinmagrez approved these changes

2020-10-26 09:59 UTC, merged