✨ add Article Card component
ZeroGachis/xamarin-ui pull request #8
Opened 2020-10-23 09:26 UTC by pewho

2020-10-23 10:03 UTC, sGeeK44 approved these changes

2020-10-23 11:04 UTC, valentinmagrez commented on Smartway.UiComponent/CardLists/ArticleCardList.xaml
> +                            ShortageAt="{Binding ShortageAt}"
Je pose la question juste pour savoir, mais du coup la on Bind la propriété Label du composant sur la propriété Label de l'item de la liste  mais ton item de la liste on est pas sur qu'il en ai un vu qu'il y a aucune contrainte de type sur l'item?

2020-10-23 12:07 UTC, pewho commented on Smartway.UiComponent/CardLists/ArticleCardList.xaml
> +                            ShortageAt="{Binding ShortageAt}"
c'est exact. Je pense que ce c'est vide si c'est pas la ...

2020-10-23 13:22 UTC, a-bertrand requested changes
Juste un petit soucis sur la taille des images  sur ton image de présentation

2020-10-26 09:13 UTC, a-bertrand approved these changes

2020-10-26 09:13 UTC, merged